### ISSUE TITLE
SA-MP servers that have > 100 players online give a timeout.

### ISSUE THREAD

**Issue by youssefdetovernickr** [sonicsnes/node-gamedig#23]
It's known that you can't retrieve the player list when there are more than 100 players online, however you still can retrieve all other data, like mapname, servername, etc. With this plugin gamedig times out with error "timeout".

Try it yourself:
Type in the console gamedig --type samp --host 93.119.26.251 --port 7777

That's the IP + port of Romania Super Stunt (some random server I got from the internet list). Has 300 players at the time of writing, got the error message timeout. If you think this only happens with this IP + port, try an other one where the player count > 100.

**Comment by xCausxn** [comment]
Confirmed, this is timing out. I will try debug it however @sonicsnes will have a better understanding :P

**Comment by youssefdetovernickr** [comment]
fast response :smile: 

Anyways thanks for spreading this awesome project and letting others use it :). I'll wait for the fix but no hurry needed.

**Comment by xCausxn** [comment]
I support this as much as i can :D i run the https://gamerlabs.net/query/ which creates a API for people to use in web apps :d 

And see data online :D

**Comment by sonicsnes** [comment]
It seems that sa:mp has some sort of issue that over a certain player limit, it entirely stops responding to player list requests. I [thought](https://github.com/sonicsnes/node-gamedig/blob/master/protocols/samp.js#L49) this was already handled in the protocol definition, but a missing callback was causing the procedure to never continue (and then get caught by the watchdog). This should be fixed in a few minutes.

I'll make a wild guess that samp is simply trying to pack every single player into a single UDP packet, which will of course fail if the player count is ridiculously high.
