### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by Netifriik** [sonicsnes/node-gamedig#30]
Is there a way to get the time it took to query the data from a server? Basically I want to display the latency between the API server and game server - it would be a nice way to get the rough latency between a player and the game server if the player is located in the same country as the api server.

**Comment by Netifriik** [comment]
I added a way to ping and get the latency of a host but I'm not sure if it's the best way to do it. https://github.com/Netifriik/node-gamedig/commit/618e19192cb7085d8eed5b5acdb5b17e11e95bff

@xCausxn what do you think? The way I implemented it - is it good/bad?

**Comment by sonicsnes** [comment]
I'm not really sure if this belongs in gamedig. Not all game server hosts will respond to pings, and at the very least, the pings should probably be done in parallel with the status query. Since not many people will use this metric, it may be better to leave it out of the library and leave it up to the user to implement separately if they want.

**Comment by xCausxn** [comment]
I agree with @sonicsnes , Its not really a true ping from the person connecting, specifically from my Web API. This will be the ping from the server to the game server so even for someone in a completely different country it will show as same.  Also if anything you would just time the round trip of the game query.
