### ISSUE TITLE
--port is not working at all.

### ISSUE THREAD

**Issue by Setitch** [sonicsnes/node-gamedig#34]
I'm running two servers (games) at one machine. On two different ports - one 7777 another 7779 (and also 27015 and 27020) thenever i use --port to gamedig i ONLY get answer from the 7777 server - never from other - even if i know its running (and i even logged into it).

**Comment by sonicsnes** [comment]
Which game are you attempting to query?

**Comment by Setitch** [comment]
ARK:SE

**Comment by sonicsnes** [comment]
Ark is unusual in that the query port for a server has no relation to the game port (see the note about [separate query ports](https://github.com/sonicsnes/node-gamedig#separate-query-port). The default install has a game port of 7777, and a query port of 27015.

Since the query port is completely unrelated to the game port for this game, as mentioned in the note, you must pass a 'port_query' parameter to gamedig (--port_query on the command line) with the query port for the server you are interested in. As far as I know, it is not possible to detect what this port is based on the connection port for the server.

**Comment by Setitch** [comment]
So this is also true for ARK not only that game, ok - good to know, thank you for answer-  can you also add that information to readme?^^

**Comment by sonicsnes** [comment]
@Setitch This is already in the readme. ARK is annotated with "[Separate Query Port]", with a link to the section down below.
