### ISSUE TITLE
Request: Tribes 1 support

### ISSUE THREAD

**Issue by ckj** [sonicsnes/node-gamedig#80]
I tried figuring out the protocol stuff based on the references provided, but I couldn't get it going.

**Comment by sonicsnes** [comment]
Added to v1.0.42 by 802027c5524252385a4035c8b0f7608428bbf472 😄

**Comment by ckj** [comment]
Nice! Works like a charm.

I'd also like to query the tribes master server at `t1m1.masters.tribesmasterserver.com:28000` to get a list of all active servers. Is there a chance I could accomplish that with this lib as well?

**Comment by sonicsnes** [comment]
I've been trying to keep master server / rcon support out of gamedig to avoid bloat, and since the response format doesn't really fit.

I've just hacked some limited support for this in `1.0.44`, but beware that it is not really supported.

Set the game type to `protocol-tribes1master`, and the host / port to that of the master server. Servers 'should' come back in the raw object of the response.

Beware that `t1m1.masters.tribesmasterserver.com:28000` always seems to time out -- I think it might be dead. I had better luck with some of the other masters like `t1m1.pu.net:28000`

**Comment by ckj** [comment]
Wow, this is incredible. Thanks so much for this package!
