### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by joao-pedro-alves** [sonicsnes/node-gamedig#99]
I'm having issues dealing with words with accent (like Portuguese). How can I set the proper encoding in order to accents be shown properly?

**Comment by sonicsnes** [comment]
This varies greatly depending on the game. What game are you having issues with?

**Comment by joao-pedro-alves** [comment]
> This varies greatly depending on the game. What game are you having issues with?

It's SAMP

**Comment by sonicsnes** [comment]
Fixed in 1.0.48. Samp uses ansi encoding rather than utf-8.

**Comment by sonicsnes** [comment]
@joao-pedro-alves I've noticed that many of the russian servers for samp use codepage 1251 rather than codepage 1252. Unfortunately, it's not very easy to detect this automatically.

If you are primarily concerned with russian servers, you should update to 1.0.49 and pass `encoding: 'win1251'` as a parameter to Gamedig. This will allow russian to work properly, but may break some other western languages.
